# github action for sync gitee codes to github

name: Sync Gitee  Repos To GenomicLab

on: 

  schedule:

    - cron: '0 22,10 * * *'

  push:

    branches: [ main ]

  delete:

    branches: [ main ]

  create:

    branches: [ main ]

    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Sync HBSIG Repos To Github  # 名字随便起

      uses: Yikun/hub-mirror-action@master  # 使用Yikun/hub-mirror-action

      with:

        src: gitee/rainoffallingstar  # 源端账户名(gitee)

        dst: github/Genomiclab   # 目的端账户名(github)

        dst_key: ${{ secrets.GH_PRIVATE_KEY }}  # SSH密钥对中的私钥

        dst_token:  ${{ secrets.GH_TOKEN }}  # Github账户的私人令牌

        account_type: org

        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh

        debug: true  # 启用后会显示所有执行命令

        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        #mappings: "Hematology_Bioinformatics_SIG => hematology-bioinformatic-sig.github.io"

        static_list: "methy2expr"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个

        timeout: '60s'  # git超时设置，超时后会自动重试git操作
