# github action for sync gitee codes to github

name: Sync Gitee Repos To Github

on: 
  workflow_dispatch:
  schedule:

    - cron: '0 22,4,10 * * *'
    
  push:

    branches: [ main ]

  delete:

    branches: [ main ]

  create:

    branches: [ main ]

    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Sync Gitee Repos To Github  # 名字随便起

      uses: Yikun/hub-mirror-action@master  # 使用Yikun/hub-mirror-action

      with:

        src: gitee/rainoffallingstar  # 源端账户名(gitee)

        dst: github/rainoffallingstar   # 目的端账户名(github)

        dst_key: ${{ secrets.GH_PRIVATE_KEY }}  # SSH密钥对中的私钥

        dst_token:  ${{ secrets.GH_TOKEN }}  # Github账户的私人令牌

        account_type: user  # 账户类型

        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh

        debug: true  # 启用后会显示所有执行命令

        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        
        #mappings: "rainoffallingstar=>rainoffallingstar.github.io"

        static_list: "systemdR,dockerR,sell,Viral-Track,deeplearing_tensorflow_shiny,deepin-rootfs-docker,path-gnn-in-ga,tgca_load_in_ga,survival-analysis-shiny,to_list_in_hefei,Data_Analysis_in_GA_workflow,DLBL-methyarrary,hemat_drug_assistant,rscript"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个

        timeout: '600s'  # git超时设置，超时后会自动重试git操作
    - name: Sync Github Repos To Gitee  # 名字随便起

      uses: Yikun/hub-mirror-action@master  # 使用Yikun/hub-mirror-action

      with:

        src: github/rainoffallingstar  # 源端账户名(gitee)

        dst: gitee/rainoffallingstar   # 目的端账户名(github)

        dst_key: ${{ secrets.GH_PRIVATE_KEY }}  # SSH密钥对中的私钥

        dst_token:  ${{ secrets.GITEE_TOKEN }}  # Github账户的私人令牌

        account_type: user  # 账户类型

        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh

        debug: true  # 启用后会显示所有执行命令

        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        
        mappings: "rainoffallingstar=>profile_rainoffallingstar"

        static_list: "rainoffallingstar,daily-rss"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个

        timeout: '60s'  # git超时设置，超时后会自动重试git操作
        
        
