# github action for sync gitee codes to github

name: Sync Github Repos To Gitee

on: 

  schedule:

    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'

  push:

    branches: [ main ]

  delete:

    branches: [ main ]

  create:

    branches: [ main ]

    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Sync Gitee Repos To Github  # 名字随便起

      uses: Yikun/hub-mirror-action@master  # 使用Yikun/hub-mirror-action

      with:

        src: gitee/rainoffalingstar  # 源端账户名(github)

        dst: github/rianoffallingstar  # 目的端账户名(gitee)

        dst_key: ${{ secrets.GH_PRIVATE_KEY }}  # SSH密钥对中的私钥

        dst_token:  ${{ secrets.GH_TOKEN }}  # Gitee账户的私人令牌

        account_type: user  # 账户类型

        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh

        debug: true  # 启用后会显示所有执行命令

        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库

        static_list: "Data_Analysis_in_GA_workflow,DLBL-methyarrary,hemat_drug_assistant"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个

        timeout: '600s'  # git超时设置，超时后会自动重试git操作
